spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://121.199.66.137:3306/WeCareLib?useUnicode=true&characterEncoder=utf-8&useSSL=true&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8082
  ssl:
    key-store: classpath:8866419_wecare.owemshu.cn.pfx
    key-store-password: K9U8Wx9i
